### PR TITLE
Rewrite rvx-builder docs and other random improvements

### PR DESCRIPTION
**Pull request by KobeW50**
This is how the README will look

image

### CODE REVIEW

**Comment by inotia00** [comment]
Why was PR closed?

**Comment by KobeW50** [comment]
Ooof i accidentally synced my branch with upstream and discarded commits. Is there a way to restore my commits?

**Comment by inotia00** [comment]
PR branch remains here
https://github.com/inotia00/revanced-documentation/tree/14feaf7c888be6e6e0e7b2cdd4ae2c04d10ae678

After downloading the PR branch, please open the new PR

**Comment by KobeW50** [comment]
Thank you. I ended up still having them locally, so i opened a new pr (i hope nothing was messed up. I'm pretty sure even my laptop is confused)

**Pull request closed without merging**
